# The RegEX template expressions
product_name_templates = (
    r'Product and Company Identification.\s.\s.\sProduct Name.+\s.+\s',
    r'SAFETY DATA SHEET\sProduct name\s.+\s',
    r'Product Code\s.+\sProduct Name\s.+\s',
    r'IDENTITY.+As Used on Label and List.+\s.+\s',
    r'Mixture identification.\sTrade name.+\s',
    r'1.1 PRODUCT IDENTIFIER.+\s.\s.\s.+\s',
    r'Business name:.+\s',
    r'Mixture\sProduct name\s.+\s',
    r'Commercial Product Name.\s.+\s.+\s',
    r'CHEMICAL PRODUCT IDENTIFICATION.+\s.+\s.+',
    r'PRODUCTIDENTIFICATIE.+\s.+\s',
    r'Mixture.\sProduct name.\s.+\s',
    r'Trade name or designation.+\sof the mixture.+\s.+\s',
    r'Product identifier\s.+Relevant identified uses of the substance or mixture and uses advised against',
    r'Product Identifier\sProduct identifier:\sOther identifiers:\s.+\s',

    r'Product identifier\s.+Trade name.+\s',
    r'Product identifier.\sProduct form.\s.+Mixture.\sTrade name.\s.+\s',
    r'Substance.Name.+\s.+\s.\s.\s',
    r'Product identifier.\s.\sCommercial ProductName.+\s.+\s',
    r'Brand.name.+\s.+\s',
    r'Identification of the substance/+preparation.+\s[A-Z]+\w[A-Z]+\w',
    r'Information on Product.+\sTrade Name.+\s.\s.\s.+\s',
    r'Commercial.name.+\s.\s.\s.+\s',

    r'Trade.name.\s:.\s.+\s',
    r'Trade name.+\s.\s.+\s.+\s',
    r'Substance.Name.+\s.\s.*\s',

    r'Product identifier.\sProduct name.\s.+\s',
    r'Product form.\s..Mixture.\sTrade name.\s.+\s',
    r'Product identifier.\sTrade name.\s.+\s',
    r'Product identifier.\s.\sCommercial Product Name.\s.\s..\s.+\s',
    r'Product identifier\sName of product\s.+\s',
    r'Product identifier.\sProduct name.\s.+\s.+\s'
    r'Product Identifier.\sProduct identifier.+\s.\s.+\s',
    r'Product identifier\sProduct name\s.+\s',
    r'Product identifier\s.+Product Name.\s.+\s',
    r'Product identifier.\s.\s.\sProduct name.+\s.+\s',
    r'Product identifier.\s.\sProduct name.+\s.+\s',
    r'Product identifier.\sProduct name.\s:\s.+\s.\s',
    r'Product identifier.\s.Product name.\s.+\s',
    r'Product identifier\sProduct name.\s.+\s',
    r'Product identifier\s.+Product Name.+\s-.*',
    r'Product identifier\sProduct form\s.+Mixture\s.+\s',
    r'Product identifier.\sName.\s.+\s',
    r'Product identifier For professional use only\s·.Trade name.+\s',
    r'Product identifier.\s.\s.\sTrade name.\s.+\s',
    r'Product identifier.\s.\sTrade name.\s.+\s.+\s',
    r'Product identifier\sTrade name.\s.+\s',
    r'Product identifier.\s.\s.\sTrade name:.+\s.+',
    r'Product identifier\s.+Trade name.\s.+\s',
    r'Product identifier.\s.\sTrade name.+\s.+\s',
    r'Product identifier.\s.+\sTrade name.+\s.+\s',
    r'Product identifier\s.+\s',
    r'Product identifier.\s.\s.+\s.\s',
    r'Product identifier.\s.\s.+\s',
    r'Product identifier.+\s.+\s.+\s.+',

    r'Product name\..\s.+\s',
    r'Product Name.\s.+\s',
    r'Product name.\s.+\s.+\s',
    r'Product name..\s.\s.+\s',
    r'Product name.+\s.+\s',
    r'Product name.+\s.\s.+\s',
    r'Trade name:.*\s.*',
    r'Trade name.+\s.+\s',
    r'Material.Name:.*\s',
    r'Product.+\s',
)


company_name_templates = (
    r'Information on the supplier submitting the Safety Data Sheet.\s.\sName of the company..\s.+\s',
    r'Information about supplier of.\smaterial safety data sheet.\s.+\s',
    r'Information on Manufacturer/Supplier..\sCompany..\s.\s.\s.\s.+\s',
    r'Supplier.(manufacturer/importer/only.representative/downstream.\suser/distributor).+\s.+\s',
    r'DETAILS OF THE SUPPLIER OF THE SAFETY DATA SHEET.\sCompany..\s.+\s',
    r'DETAILS OF THE SUPPLIER OF THE SAFETY DATA SHEET..\s.+\s',
    r'Supplier/Manufacturer.\sDistributor or Importer\s.+\s',
    r'Company/Undertaking Identification..\sSupplier.\s.+\s',
    r'MANUFACTURER INFORMATION..\s.+\s',
    r'SUPPLIER OF THE SAFETY DATA SHEET.\s.+\s',
    r'Producer.\sIdentification.\s.+\s',
    r'No additional information available.\s.\s.\s.+\s',

    r'Identification of the.\scompany..\s.+\s',
    r'Details of the supplier of the safety data sheet..\sSupplier..\s.\s.\s.+\s',
    r'Details of the supplier of the safety data sheet.\sSupplier..\s.\s.+\s',
    r'Details Of The Supplier Of The Safety Data Sheet.+\s.+\sCompany Identification.+\s',
    r'Details of the supplier of the safety data sheet.\s.\sManufacturer.+\s.\s.+\s',
    r'Details of the supplier of the safety data sheet..\sSupplier..\sName.+\s',
    r'Details of the supplier of the safety data sheet.\s.\sSupplier.+\s.+\s',
    r'Details of the supplier of the safety data sheet.+\sSupplier.+\s.+\s',
    r'Details of the supplier of the Safety Data Sheet.\sCompany Name..\s.+\s',
    r'Details of the supplier of the safety data sheet\sCompany name.\s.+\s',    
    r'Details of the supplier of the safety data sheet\sCompany.+\s',
    r'Details of the supplier of the safety data sheet.\s.Name.\s.+\s',
    r'Details of the supplier of the safety data sheet\sSupplier\s.+\s',
    r'Details of the supplier of the safety data sheet\sDistributor\s.+\s',
    r'Details of the supplier of the safety data sheet..\s.+\s.+\s',
    r'Details of the supplier of the safety data sheet.\s.+\s.+\s',
    r'Details of the supplier of the safety data sheet.\s.+\s',
    r'Details of the supplier of the safety data sheet.+\s.+\s',
    r'Details of the supplier of the safety\s.+\s',
    r'Supplier of the safety data sheet\sDistributor of.+\s.+\s',
    r'Supplier of the safety data sheet.\s.\s.+\s',

    r'Responsible person for the safety data sheet.\sName..\s.+\s',
    r'Brand names..\s.+\s',

    r'MANUFACTURER..\s.+\s',
    r'Manufacturer’s Name.+\s.\s.+\s',
    r'Manufacturer/Supplier..\s.+\s',
    r'Manufacturer/Supplier.\s.+\s',
    r'Manufacturer/Supplier.+\s.\s.+\s',
    r'Manufacturer..Supplier.+\s.+\s',
    r'Manufacturer/Supplier.+\s',
    r'Manufacturer..\s.\s.+\s',
    r'Manufacturer.+\s.+\s',


    r'Supplier details..\s.+\s',
    r'Manufacturer.\s.+\s',
    r'Supplier.\s.\s.\s.+\s',
    r'Supplier.\s.\s.+\s',

    r'Company name..\s.\s.+\s',
    r'Company name.\s.+\s',
    r'Company.\s.\s.\s..\s.+\s',
    r'Company.\s.\s.\s.+\s',

    r'Company Identification.\sManufactured by.\s.+\s',
    r'Company identification..\s.\s.+\s',
    r'Company Identification.\s.+\s',
    r'Company Identification.+\s',

    r'Supplier..\s.\s.\s.\s.+\s',
    r'Supplier..\s.\s.\s.+\s',
    r'Supplier.+\s.\s.\s.\s.+\s',
    r'Supplier\s.+\s',
    r'Supplier..\s.+\s',
    r'Supplier.\s.+\s',

    r'Company.\s.+\s.+\s',
    r'Company.+\s',
    r'Supplier.+\s.+\s',
)


email_templates = (
    r'\w.+@.+\.com\w',
    r'\w.+@.+\.dk\w',
    r'\w.+@.+\.de\w',
    r'\w.+@.+\.uk\w',
    r'\w.+@.+\.cz\w',
    r'\w.+@.+\.eu\w'
    r'\w.*[@].*\w',
    r'\w.*[@].*\w',
)



